// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using oficinaCovid.App.Persistencia;

namespace oficinaCovid.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211014021602_5_Migracion")]
    partial class _5_Migracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("oficinaCovid.App.Dominio.Diagnostico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("diasAislamiento")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaDiagnostico")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaFinAislamiento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("infectado")
                        .HasColumnType("bit");

                    b.Property<int?>("personaid")
                        .HasColumnType("int");

                    b.Property<int?>("sintomasid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("personaid");

                    b.HasIndex("sintomasid");

                    b.ToTable("diagnosticos");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Disponibilidad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("disponible")
                        .HasColumnType("bit");

                    b.Property<DateTime>("hora")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("horasDisponibles");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Gobernacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numeroOficinas")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("gobernaciones");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.GobernacionProveedor", b =>
                {
                    b.Property<int>("gobernacionId")
                        .HasColumnType("int");

                    b.Property<int>("proveedorId")
                        .HasColumnType("int");

                    b.HasKey("gobernacionId", "proveedorId");

                    b.HasIndex("proveedorId");

                    b.ToTable("GobernacionProveedor");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Oficina", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("aforo")
                        .HasColumnType("int");

                    b.Property<int?>("gobernacionid")
                        .HasColumnType("int");

                    b.Property<string>("numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("secretarioid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("gobernacionid");

                    b.HasIndex("secretarioid");

                    b.ToTable("oficinas");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.OficinaVisitante", b =>
                {
                    b.Property<int>("oficinaId")
                        .HasColumnType("int");

                    b.Property<int>("visitanteId")
                        .HasColumnType("int");

                    b.HasKey("oficinaId", "visitanteId");

                    b.HasIndex("visitanteId");

                    b.ToTable("oficinaVisitante");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<string>("genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombres")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.SintomasCovid", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("desaliento")
                        .HasColumnType("bit");

                    b.Property<bool>("dificultadRespirar")
                        .HasColumnType("bit");

                    b.Property<bool>("dolorGarganta")
                        .HasColumnType("bit");

                    b.Property<bool>("fiebre")
                        .HasColumnType("bit");

                    b.Property<bool>("perdidaGusto")
                        .HasColumnType("bit");

                    b.Property<bool>("perdidaOlfato")
                        .HasColumnType("bit");

                    b.Property<bool>("tosSeca")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("sintomas");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.GobernadorAsesor", b =>
                {
                    b.HasBaseType("oficinaCovid.App.Dominio.Persona");

                    b.Property<string>("rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("GobernadorAsesor");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.PersonalAseo", b =>
                {
                    b.HasBaseType("oficinaCovid.App.Dominio.Persona");

                    b.Property<int?>("gobernacionid")
                        .HasColumnType("int");

                    b.Property<string>("horaIngreso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horaSalida")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("gobernacionid");

                    b.HasDiscriminator().HasValue("PersonalAseo");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.PersonalProveedor", b =>
                {
                    b.HasBaseType("oficinaCovid.App.Dominio.Persona");

                    b.Property<string>("nombreEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("servicioRealizado")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PersonalProveedor");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.SecretarioDespacho", b =>
                {
                    b.HasBaseType("oficinaCovid.App.Dominio.Persona");

                    b.Property<int?>("gobernacionid")
                        .HasColumnType("int")
                        .HasColumnName("SecretarioDespacho_gobernacionid");

                    b.HasIndex("gobernacionid");

                    b.HasDiscriminator().HasValue("SecretarioDespacho");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Diagnostico", b =>
                {
                    b.HasOne("oficinaCovid.App.Dominio.Persona", "persona")
                        .WithMany()
                        .HasForeignKey("personaid");

                    b.HasOne("oficinaCovid.App.Dominio.SintomasCovid", "sintomas")
                        .WithMany()
                        .HasForeignKey("sintomasid");

                    b.Navigation("persona");

                    b.Navigation("sintomas");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.GobernacionProveedor", b =>
                {
                    b.HasOne("oficinaCovid.App.Dominio.Gobernacion", "gobernacion")
                        .WithMany()
                        .HasForeignKey("gobernacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oficinaCovid.App.Dominio.PersonalProveedor", "proveedor")
                        .WithMany()
                        .HasForeignKey("proveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("gobernacion");

                    b.Navigation("proveedor");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Oficina", b =>
                {
                    b.HasOne("oficinaCovid.App.Dominio.Gobernacion", "gobernacion")
                        .WithMany()
                        .HasForeignKey("gobernacionid");

                    b.HasOne("oficinaCovid.App.Dominio.SecretarioDespacho", "secretario")
                        .WithMany()
                        .HasForeignKey("secretarioid");

                    b.Navigation("gobernacion");

                    b.Navigation("secretario");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.OficinaVisitante", b =>
                {
                    b.HasOne("oficinaCovid.App.Dominio.Oficina", "oficina")
                        .WithMany()
                        .HasForeignKey("oficinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("oficinaCovid.App.Dominio.GobernadorAsesor", "visitante")
                        .WithMany()
                        .HasForeignKey("visitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("oficina");

                    b.Navigation("visitante");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.PersonalAseo", b =>
                {
                    b.HasOne("oficinaCovid.App.Dominio.Gobernacion", "gobernacion")
                        .WithMany()
                        .HasForeignKey("gobernacionid");

                    b.Navigation("gobernacion");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.SecretarioDespacho", b =>
                {
                    b.HasOne("oficinaCovid.App.Dominio.Gobernacion", "gobernacion")
                        .WithMany()
                        .HasForeignKey("gobernacionid");

                    b.Navigation("gobernacion");
                });
#pragma warning restore 612, 618
        }
    }
}
