// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using oficinaCovid.App.Persistencia;

namespace oficinaCovid.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211014013900_Tercera")]
    partial class Tercera
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("oficinaCovid.App.Dominio.Diagnostico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("DiasAislamiento")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDiagnostico")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFinAislamiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<bool>("Positivo")
                        .HasColumnType("bit");

                    b.Property<int?>("SintomatologiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("SintomatologiaId");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Gobernacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroOficinas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gobernaciones");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Oficina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Aforo")
                        .HasColumnType("int");

                    b.Property<int?>("GobernacionId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecretarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GobernacionId");

                    b.HasIndex("SecretarioId");

                    b.ToTable("Oficinas");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Sintomatologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Desaliento")
                        .HasColumnType("bit");

                    b.Property<bool>("DificultadRespirar")
                        .HasColumnType("bit");

                    b.Property<bool>("DolorGarganta")
                        .HasColumnType("bit");

                    b.Property<bool>("Fiebre")
                        .HasColumnType("bit");

                    b.Property<bool>("PerdidaGusto")
                        .HasColumnType("bit");

                    b.Property<bool>("PerdidaOlfato")
                        .HasColumnType("bit");

                    b.Property<bool>("TosSeca")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Sintomatologias");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Visita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OficinaId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OficinaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Visitas");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Administrativo", b =>
                {
                    b.HasBaseType("oficinaCovid.App.Dominio.Persona");

                    b.Property<int?>("GobernacionId")
                        .HasColumnType("int")
                        .HasColumnName("Administrativo_GobernacionId");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("GobernacionId");

                    b.HasDiscriminator().HasValue("Administrativo");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Aseador", b =>
                {
                    b.HasBaseType("oficinaCovid.App.Dominio.Persona");

                    b.Property<int?>("GobernacionId")
                        .HasColumnType("int");

                    b.HasIndex("GobernacionId");

                    b.HasDiscriminator().HasValue("Aseador");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Proveedor", b =>
                {
                    b.HasBaseType("oficinaCovid.App.Dominio.Persona");

                    b.Property<int?>("GobernacionId")
                        .HasColumnType("int")
                        .HasColumnName("Proveedor_GobernacionId");

                    b.Property<string>("Servicio")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("GobernacionId");

                    b.HasDiscriminator().HasValue("Proveedor");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Secretario", b =>
                {
                    b.HasBaseType("oficinaCovid.App.Dominio.Persona");

                    b.Property<int?>("GobernacionId")
                        .HasColumnType("int")
                        .HasColumnName("Secretario_GobernacionId");

                    b.HasIndex("GobernacionId");

                    b.HasDiscriminator().HasValue("Secretario");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Diagnostico", b =>
                {
                    b.HasOne("oficinaCovid.App.Dominio.Persona", null)
                        .WithMany("Diagnosticos")
                        .HasForeignKey("PersonaId");

                    b.HasOne("oficinaCovid.App.Dominio.Sintomatologia", "Sintomatologia")
                        .WithMany()
                        .HasForeignKey("SintomatologiaId");

                    b.Navigation("Sintomatologia");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Oficina", b =>
                {
                    b.HasOne("oficinaCovid.App.Dominio.Gobernacion", null)
                        .WithMany("Oficinas")
                        .HasForeignKey("GobernacionId");

                    b.HasOne("oficinaCovid.App.Dominio.Secretario", "Secretario")
                        .WithMany()
                        .HasForeignKey("SecretarioId");

                    b.Navigation("Secretario");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Visita", b =>
                {
                    b.HasOne("oficinaCovid.App.Dominio.Oficina", "Oficina")
                        .WithMany()
                        .HasForeignKey("OficinaId");

                    b.HasOne("oficinaCovid.App.Dominio.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId");

                    b.Navigation("Oficina");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Administrativo", b =>
                {
                    b.HasOne("oficinaCovid.App.Dominio.Gobernacion", null)
                        .WithMany("Administrativos")
                        .HasForeignKey("GobernacionId");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Aseador", b =>
                {
                    b.HasOne("oficinaCovid.App.Dominio.Gobernacion", null)
                        .WithMany("Aseadores")
                        .HasForeignKey("GobernacionId");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Proveedor", b =>
                {
                    b.HasOne("oficinaCovid.App.Dominio.Gobernacion", null)
                        .WithMany("Proveedores")
                        .HasForeignKey("GobernacionId");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Secretario", b =>
                {
                    b.HasOne("oficinaCovid.App.Dominio.Gobernacion", null)
                        .WithMany("Secretarios")
                        .HasForeignKey("GobernacionId");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Gobernacion", b =>
                {
                    b.Navigation("Administrativos");

                    b.Navigation("Aseadores");

                    b.Navigation("Oficinas");

                    b.Navigation("Proveedores");

                    b.Navigation("Secretarios");
                });

            modelBuilder.Entity("oficinaCovid.App.Dominio.Persona", b =>
                {
                    b.Navigation("Diagnosticos");
                });
#pragma warning restore 612, 618
        }
    }
}
